collections:
  jobs:
  papers:
    output: true
  people:
    output: true
    permalink: /:path
  newpeople:
    output: true
    permalink: /people/:path
defaults:
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "member"
paginate: 8
paginate_path: "/news/page:num"
permalink: pretty
